//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputAction_0.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Project_II.InputSystem
{
    public partial class @InputAction_0: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputAction_0()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputAction_0"",
    ""maps"": [
        {
            ""name"": ""Character"",
            ""id"": ""9dd4d344-debb-463d-adbd-0d7d0b03366f"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""cf443539-b5d3-4d3d-be87-065213654212"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""run"",
                    ""type"": ""Button"",
                    ""id"": ""2de6a8a5-2099-4629-8c3a-e601b1c97661"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""sneak"",
                    ""type"": ""Button"",
                    ""id"": ""fdc8964d-a416-4424-bbfb-23e2a18a8654"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mouse"",
                    ""type"": ""Value"",
                    ""id"": ""c281247a-1d14-4ad7-a8c1-9ce9e072c695"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""mainAttack"",
                    ""type"": ""Button"",
                    ""id"": ""77ba8af3-9912-4ead-ab78-30fa14244aab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""secondaryAttack"",
                    ""type"": ""Button"",
                    ""id"": ""38df79d7-d5d8-49ca-b522-e32b6b71ab0f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""reload"",
                    ""type"": ""Button"",
                    ""id"": ""50445c56-1cd4-442b-93be-037a1a6c838e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""interaction"",
                    ""type"": ""Button"",
                    ""id"": ""ebe66e4c-9608-4b73-b144-1e8494ada9d0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switch_0"",
                    ""type"": ""Button"",
                    ""id"": ""45558cc5-9d5f-4217-8a0e-d536867b91d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switch_1"",
                    ""type"": ""Button"",
                    ""id"": ""0cac5533-ee74-4b9d-a654-38a00346814e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switch_2"",
                    ""type"": ""Button"",
                    ""id"": ""29d01b54-26f4-4ef6-8b78-eb00a64804e6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switch_3"",
                    ""type"": ""Button"",
                    ""id"": ""b460337d-2939-4f5f-98b9-283ea04d0c1a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switch_4"",
                    ""type"": ""Button"",
                    ""id"": ""5d394f00-f46a-4978-8a3f-79ad47a9bf0d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switch_5"",
                    ""type"": ""Button"",
                    ""id"": ""865351cc-0a7f-4829-bd40-5199ddbe9afb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switchBackPack"",
                    ""type"": ""Button"",
                    ""id"": ""494183f2-4701-41ac-9928-2ecd08365368"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""acdd43e0-ccd3-43fb-88c6-00928aa52380"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d8586f3b-0a66-4e87-be2f-7387e9977770"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""43bb98fb-c50f-44ed-b5e8-a931a1abc90b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c9a0302b-46ca-4ec0-8729-dbd248471c92"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""78693b66-1492-4c26-8a3b-5c3d76bffcda"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d022829a-09c9-4fbf-ab54-713b56737a75"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d865bb8-42e4-49fe-93d0-a6c1671cd86d"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05fd00c6-2356-4485-a8b5-91a8f8affc74"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sneak"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0713002d-004b-4f01-a245-ec8929051b0d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91cbef10-bd16-41ea-a4b2-c1f6f2352480"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0307d8cc-85af-487b-aa10-58eb0966797b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mainAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6aa0423a-eae6-47e7-ae3f-a50e02cd4975"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mainAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c4e6f2d-981f-403a-8b40-7d1dc61ab50c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""secondaryAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f5d4135-95f1-4d4a-b6ec-dfa6255c791c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""secondaryAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fddce858-f7ab-40f7-b852-47d6ae9b5003"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f887dfed-9c97-4bec-ad9f-d10ad6d9b0f3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""089ded12-34b7-4678-b616-e7d5c57600d0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc2c1ccb-9654-4213-84db-dd69e5d32665"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switch_0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e806c70a-46d5-4304-beec-eb68c93f6a74"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switch_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f456e50-7e49-4dd2-8ee1-1029824fabe7"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switch_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b799146c-08ea-4a5d-a4eb-2cba31dd1ad7"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switch_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdee5da1-0090-4276-8f86-232b5fe7c50c"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switch_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21894ff3-5acb-4fe8-83af-b9f044ba9ec7"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switch_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dbddbba-40d6-4752-bb40-d35d354ba022"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switchBackPack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Character
            m_Character = asset.FindActionMap("Character", throwIfNotFound: true);
            m_Character_move = m_Character.FindAction("move", throwIfNotFound: true);
            m_Character_run = m_Character.FindAction("run", throwIfNotFound: true);
            m_Character_sneak = m_Character.FindAction("sneak", throwIfNotFound: true);
            m_Character_mouse = m_Character.FindAction("mouse", throwIfNotFound: true);
            m_Character_mainAttack = m_Character.FindAction("mainAttack", throwIfNotFound: true);
            m_Character_secondaryAttack = m_Character.FindAction("secondaryAttack", throwIfNotFound: true);
            m_Character_reload = m_Character.FindAction("reload", throwIfNotFound: true);
            m_Character_interaction = m_Character.FindAction("interaction", throwIfNotFound: true);
            m_Character_switch_0 = m_Character.FindAction("switch_0", throwIfNotFound: true);
            m_Character_switch_1 = m_Character.FindAction("switch_1", throwIfNotFound: true);
            m_Character_switch_2 = m_Character.FindAction("switch_2", throwIfNotFound: true);
            m_Character_switch_3 = m_Character.FindAction("switch_3", throwIfNotFound: true);
            m_Character_switch_4 = m_Character.FindAction("switch_4", throwIfNotFound: true);
            m_Character_switch_5 = m_Character.FindAction("switch_5", throwIfNotFound: true);
            m_Character_switchBackPack = m_Character.FindAction("switchBackPack", throwIfNotFound: true);
        }

        ~@InputAction_0()
        {
            UnityEngine.Debug.Assert(!m_Character.enabled, "This will cause a leak and performance issues, InputAction_0.Character.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Character
        private readonly InputActionMap m_Character;
        private List<ICharacterActions> m_CharacterActionsCallbackInterfaces = new List<ICharacterActions>();
        private readonly InputAction m_Character_move;
        private readonly InputAction m_Character_run;
        private readonly InputAction m_Character_sneak;
        private readonly InputAction m_Character_mouse;
        private readonly InputAction m_Character_mainAttack;
        private readonly InputAction m_Character_secondaryAttack;
        private readonly InputAction m_Character_reload;
        private readonly InputAction m_Character_interaction;
        private readonly InputAction m_Character_switch_0;
        private readonly InputAction m_Character_switch_1;
        private readonly InputAction m_Character_switch_2;
        private readonly InputAction m_Character_switch_3;
        private readonly InputAction m_Character_switch_4;
        private readonly InputAction m_Character_switch_5;
        private readonly InputAction m_Character_switchBackPack;
        public struct CharacterActions
        {
            private @InputAction_0 m_Wrapper;
            public CharacterActions(@InputAction_0 wrapper) { m_Wrapper = wrapper; }
            public InputAction @move => m_Wrapper.m_Character_move;
            public InputAction @run => m_Wrapper.m_Character_run;
            public InputAction @sneak => m_Wrapper.m_Character_sneak;
            public InputAction @mouse => m_Wrapper.m_Character_mouse;
            public InputAction @mainAttack => m_Wrapper.m_Character_mainAttack;
            public InputAction @secondaryAttack => m_Wrapper.m_Character_secondaryAttack;
            public InputAction @reload => m_Wrapper.m_Character_reload;
            public InputAction @interaction => m_Wrapper.m_Character_interaction;
            public InputAction @switch_0 => m_Wrapper.m_Character_switch_0;
            public InputAction @switch_1 => m_Wrapper.m_Character_switch_1;
            public InputAction @switch_2 => m_Wrapper.m_Character_switch_2;
            public InputAction @switch_3 => m_Wrapper.m_Character_switch_3;
            public InputAction @switch_4 => m_Wrapper.m_Character_switch_4;
            public InputAction @switch_5 => m_Wrapper.m_Character_switch_5;
            public InputAction @switchBackPack => m_Wrapper.m_Character_switchBackPack;
            public InputActionMap Get() { return m_Wrapper.m_Character; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
            public void AddCallbacks(ICharacterActions instance)
            {
                if (instance == null || m_Wrapper.m_CharacterActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CharacterActionsCallbackInterfaces.Add(instance);
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @run.started += instance.OnRun;
                @run.performed += instance.OnRun;
                @run.canceled += instance.OnRun;
                @sneak.started += instance.OnSneak;
                @sneak.performed += instance.OnSneak;
                @sneak.canceled += instance.OnSneak;
                @mouse.started += instance.OnMouse;
                @mouse.performed += instance.OnMouse;
                @mouse.canceled += instance.OnMouse;
                @mainAttack.started += instance.OnMainAttack;
                @mainAttack.performed += instance.OnMainAttack;
                @mainAttack.canceled += instance.OnMainAttack;
                @secondaryAttack.started += instance.OnSecondaryAttack;
                @secondaryAttack.performed += instance.OnSecondaryAttack;
                @secondaryAttack.canceled += instance.OnSecondaryAttack;
                @reload.started += instance.OnReload;
                @reload.performed += instance.OnReload;
                @reload.canceled += instance.OnReload;
                @interaction.started += instance.OnInteraction;
                @interaction.performed += instance.OnInteraction;
                @interaction.canceled += instance.OnInteraction;
                @switch_0.started += instance.OnSwitch_0;
                @switch_0.performed += instance.OnSwitch_0;
                @switch_0.canceled += instance.OnSwitch_0;
                @switch_1.started += instance.OnSwitch_1;
                @switch_1.performed += instance.OnSwitch_1;
                @switch_1.canceled += instance.OnSwitch_1;
                @switch_2.started += instance.OnSwitch_2;
                @switch_2.performed += instance.OnSwitch_2;
                @switch_2.canceled += instance.OnSwitch_2;
                @switch_3.started += instance.OnSwitch_3;
                @switch_3.performed += instance.OnSwitch_3;
                @switch_3.canceled += instance.OnSwitch_3;
                @switch_4.started += instance.OnSwitch_4;
                @switch_4.performed += instance.OnSwitch_4;
                @switch_4.canceled += instance.OnSwitch_4;
                @switch_5.started += instance.OnSwitch_5;
                @switch_5.performed += instance.OnSwitch_5;
                @switch_5.canceled += instance.OnSwitch_5;
                @switchBackPack.started += instance.OnSwitchBackPack;
                @switchBackPack.performed += instance.OnSwitchBackPack;
                @switchBackPack.canceled += instance.OnSwitchBackPack;
            }

            private void UnregisterCallbacks(ICharacterActions instance)
            {
                @move.started -= instance.OnMove;
                @move.performed -= instance.OnMove;
                @move.canceled -= instance.OnMove;
                @run.started -= instance.OnRun;
                @run.performed -= instance.OnRun;
                @run.canceled -= instance.OnRun;
                @sneak.started -= instance.OnSneak;
                @sneak.performed -= instance.OnSneak;
                @sneak.canceled -= instance.OnSneak;
                @mouse.started -= instance.OnMouse;
                @mouse.performed -= instance.OnMouse;
                @mouse.canceled -= instance.OnMouse;
                @mainAttack.started -= instance.OnMainAttack;
                @mainAttack.performed -= instance.OnMainAttack;
                @mainAttack.canceled -= instance.OnMainAttack;
                @secondaryAttack.started -= instance.OnSecondaryAttack;
                @secondaryAttack.performed -= instance.OnSecondaryAttack;
                @secondaryAttack.canceled -= instance.OnSecondaryAttack;
                @reload.started -= instance.OnReload;
                @reload.performed -= instance.OnReload;
                @reload.canceled -= instance.OnReload;
                @interaction.started -= instance.OnInteraction;
                @interaction.performed -= instance.OnInteraction;
                @interaction.canceled -= instance.OnInteraction;
                @switch_0.started -= instance.OnSwitch_0;
                @switch_0.performed -= instance.OnSwitch_0;
                @switch_0.canceled -= instance.OnSwitch_0;
                @switch_1.started -= instance.OnSwitch_1;
                @switch_1.performed -= instance.OnSwitch_1;
                @switch_1.canceled -= instance.OnSwitch_1;
                @switch_2.started -= instance.OnSwitch_2;
                @switch_2.performed -= instance.OnSwitch_2;
                @switch_2.canceled -= instance.OnSwitch_2;
                @switch_3.started -= instance.OnSwitch_3;
                @switch_3.performed -= instance.OnSwitch_3;
                @switch_3.canceled -= instance.OnSwitch_3;
                @switch_4.started -= instance.OnSwitch_4;
                @switch_4.performed -= instance.OnSwitch_4;
                @switch_4.canceled -= instance.OnSwitch_4;
                @switch_5.started -= instance.OnSwitch_5;
                @switch_5.performed -= instance.OnSwitch_5;
                @switch_5.canceled -= instance.OnSwitch_5;
                @switchBackPack.started -= instance.OnSwitchBackPack;
                @switchBackPack.performed -= instance.OnSwitchBackPack;
                @switchBackPack.canceled -= instance.OnSwitchBackPack;
            }

            public void RemoveCallbacks(ICharacterActions instance)
            {
                if (m_Wrapper.m_CharacterActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICharacterActions instance)
            {
                foreach (var item in m_Wrapper.m_CharacterActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CharacterActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CharacterActions @Character => new CharacterActions(this);
        public interface ICharacterActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnRun(InputAction.CallbackContext context);
            void OnSneak(InputAction.CallbackContext context);
            void OnMouse(InputAction.CallbackContext context);
            void OnMainAttack(InputAction.CallbackContext context);
            void OnSecondaryAttack(InputAction.CallbackContext context);
            void OnReload(InputAction.CallbackContext context);
            void OnInteraction(InputAction.CallbackContext context);
            void OnSwitch_0(InputAction.CallbackContext context);
            void OnSwitch_1(InputAction.CallbackContext context);
            void OnSwitch_2(InputAction.CallbackContext context);
            void OnSwitch_3(InputAction.CallbackContext context);
            void OnSwitch_4(InputAction.CallbackContext context);
            void OnSwitch_5(InputAction.CallbackContext context);
            void OnSwitchBackPack(InputAction.CallbackContext context);
        }
    }
}
